### ISSUE TITLE
Add gif illustrating expression

### ISSUE THREAD

**Issue by mvfsillva** [mvfsillva/dialetus#60]

**Comment by brunopulis** [comment]
Hey, @mvfsillva I think it's a great idea, but how we can describe from everybody? 

One of the big challenges of accessibility is how to describe gif images.

If the images are random, what is the criterion for describing the images? Maybe using an AI type an of Instagram would be ideal since it hits the description in 98% of cases.

**Comment by mvfsillva** [comment]
Great points @brunopulis, does it help me to think of a way to do this?

I think Instagram is a big case of accessibility, it would be great if we could do it here
